apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
          ports:
            - containerPort: 9090
      volumes:
        - name: prometheus-config
          persistentVolumeClaim:
            claimName: prometheus-config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
