apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: shop-service
          image: shop-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "ecommerce_db"

---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  type: ClusterIP
  selector:
    app: shop-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
